---
apiVersion: 'kci.rocks/v1alpha1'
kind: Database
metadata:
  name: backend-todo
  namespace: practice
spec:
  secretName: backend-todo-db-credentials
  instance: generic-db
  deletionProtected: false
  backup:
    enable: false
    cron: '0 0 * * *'
