apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-todo
  namespace: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-todo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-todo
    spec:
      volumes:
      containers:
        - name: backend-todo
          image: ghcr.io/tfk70/app:1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: do
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: backend-todo-db-credentials
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: backend-todo-db-credentials
            - name: DATABASE_PORT
              value: 5432
            - name: DATABASE_URL
              value: 0.0.0.0
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: backend-todo-db-credentials    
