apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: backend-todo.io
    http:
      paths:
      - path: /
        backend:
          service:
            name: backend-todo
            port:
              number: 8080
