apiVersion: v1
kind: Service
metadata:
  name: pseudo-ingress
  namespace: practice
  labels:
    app: pseudo-ingress
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    service: backend-todo
  type: NodePort
